name: tuihub_protos
description: protobuf protocol files for TuiHub
version: 0.0.1
homepage: https://github.com/tuihub/protos

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  grpc: ^4.2.0
  protobuf: 5.1.0
  fixnum: ^1.1.1